### ISSUE TITLE
where is main.py ? 

### ISSUE THREAD

**Issue by Flutevishnu** [0xZee/TravelPlanner-CrewAi-Agents-streamlit#1]

**Comment by 0xZee** [comment]
Thanks for the notice and sorry for the delay.
Actually, you have to Run : `streamlit run TravelCrewApp.py`
Repo updated (app.py -> TravelCrewApp.py)

**Comment by 0xZee** [comment]
To run the App : `streamlit run TravelCrewApp.py`
